let comidas = ["sorvete","pizza","yakisoba", "escondidinho","acaraje"]
console.log(comidas[0])
console.log(comidas[1])
console.log(comidas[2])
console.log(comidas[3])
console.log(comidas[4])
comidas[1] = prompt("qual a sua comida preferida?")
console.log(comidas[0])
console.log(comidas[1])
console.log(comidas[2])
console.log(comidas[3])
console.log(comidas[4])
