let questao1 = prompt("Qual o seu hobby?")
let questao2 = prompt("qual a sua cor favorita?")
let questao3 = prompt("O que você estudou?")
let questao4 = prompt("quanto é 1+1?")
let questao5 = prompt("qual o sentido da vida?")
console.log("1. Qual o seu hobby?")
console.log("resposta:", questao1)
console.log("2. Qual a sua cor favorita?")
console.log("resposta:", questao2)
console.log("3. O que você estudou")
console.log("resposta:", questao3)
console.log("4. Quanto é 1 + 1?")
console.log("resposta:", questao4)
console.log("5. Qual o sentido da vida")
console.log("resposta:", questao5)